version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: my_mysql_db
    restart: always
    env_file:
      - secrets.env
    environment:
      - MYSQL_DATABASE=bverse
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"