name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.0'

    - name: Install Root Dependencies
      run: npm install

    - name: Build Frontend
      run: npm run build:fe  # Use the script defined for building the frontend

    - name: Build Backend
      run: npm --prefix ./nest-server run build  # Ensures backend build is executed

    # ... continue with your deployment steps as previously defined ...