export interface PlayingCard {
  name: string;
  description: string;
  emoji: string;
  suit: "Hearts" | "Diamonds" | "Clubs" | "Spades";
  rank: string;
  element: "water" | "earth" | "fire" | "air";
}

export const playingCards: PlayingCard[] = [
  // Hearts
  {
    name: "Ace of Hearts",
    description: "The ace of hearts - love, emotion, passion",
    emoji: "🂱",
    suit: "Hearts",
    rank: "Ace",
    element: "water",
  },
  {
    name: "Two of Hearts",
    description: "The two of hearts - partnership, connection, balance",
    emoji: "🂲",
    suit: "Hearts",
    rank: "2",
    element: "water",
  },
  {
    name: "Three of Hearts",
    description: "The three of hearts - friendship, celebration, joy",
    emoji: "🂳",
    suit: "Hearts",
    rank: "3",
    element: "water",
  },
  {
    name: "Four of Hearts",
    description: "The four of hearts - stability, harmony, contentment",
    emoji: "🂴",
    suit: "Hearts",
    rank: "4",
    element: "water",
  },
  {
    name: "Five of Hearts",
    description: "The five of hearts - loss, disappointment, emotional conflict",
    emoji: "🂵",
    suit: "Hearts",
    rank: "5",
    element: "water",
  },
  {
    name: "Six of Hearts",
    description: "The six of hearts - nostalgia, childhood, innocence",
    emoji: "🂶",
    suit: "Hearts",
    rank: "6",
    element: "water",
  },
  {
    name: "Seven of Hearts",
    description: "The seven of hearts - choices, daydreams, wishful thinking",
    emoji: "🂷",
    suit: "Hearts",
    rank: "7",
    element: "water",
  },
  {
    name: "Eight of Hearts",
    description: "The eight of hearts - abandonment, withdrawal, searching",
    emoji: "🂸",
    suit: "Hearts",
    rank: "8",
    element: "water",
  },
  {
    name: "Nine of Hearts",
    description: "The nine of hearts - satisfaction, contentment, wish fulfillment",
    emoji: "🂹",
    suit: "Hearts",
    rank: "9",
    element: "water",
  },
  {
    name: "Ten of Hearts",
    description: "The ten of hearts - happiness, fulfillment, emotional completion",
    emoji: "🂺",
    suit: "Hearts",
    rank: "10",
    element: "water",
  },
  {
    name: "Jack of Hearts",
    description: "The jack of hearts - romantic, charming, emotional messenger",
    emoji: "🂻",
    suit: "Hearts",
    rank: "Jack",
    element: "water",
  },
  {
    name: "Queen of Hearts",
    description: "The queen of hearts - compassionate, loving, emotionally intelligent",
    emoji: "🂽",
    suit: "Hearts",
    rank: "Queen",
    element: "water",
  },
  {
    name: "King of Hearts",
    description: "The king of hearts - emotional balance, diplomacy, compassion",
    emoji: "🂾",
    suit: "Hearts",
    rank: "King",
    element: "water",
  },
  
  // Diamonds
  {
    name: "Ace of Diamonds",
    description: "The ace of diamonds - new opportunity, manifestation, abundance",
    emoji: "🃁",
    suit: "Diamonds",
    rank: "Ace",
    element: "earth",
  },
  {
    name: "Two of Diamonds",
    description: "The two of diamonds - balance, priorities, time management",
    emoji: "🃂",
    suit: "Diamonds",
    rank: "2",
    element: "earth",
  },
  {
    name: "Three of Diamonds",
    description: "The three of diamonds - teamwork, collaboration, building",
    emoji: "🃃",
    suit: "Diamonds",
    rank: "3",
    element: "earth",
  },
  {
    name: "Four of Diamonds",
    description: "The four of diamonds - stability, security, control",
    emoji: "🃄",
    suit: "Diamonds",
    rank: "4",
    element: "earth",
  },
  {
    name: "Five of Diamonds",
    description: "The five of diamonds - insecurity, loss, financial worry",
    emoji: "🃅",
    suit: "Diamonds",
    rank: "5",
    element: "earth",
  },
  {
    name: "Six of Diamonds",
    description: "The six of diamonds - generosity, sharing, giving and receiving",
    emoji: "🃆",
    suit: "Diamonds",
    rank: "6",
    element: "earth",
  },
  {
    name: "Seven of Diamonds",
    description: "The seven of diamonds - long-term investment, perseverance, patience",
    emoji: "🃇",
    suit: "Diamonds",
    rank: "7",
    element: "earth",
  },
  {
    name: "Eight of Diamonds",
    description: "The eight of diamonds - skill development, mastery, quality",
    emoji: "🃈",
    suit: "Diamonds",
    rank: "8",
    element: "earth",
  },
  {
    name: "Nine of Diamonds",
    description: "The nine of diamonds - rewards, luxury, self-sufficiency",
    emoji: "🃉",
    suit: "Diamonds",
    rank: "9",
    element: "earth",
  },
  {
    name: "Ten of Diamonds",
    description: "The ten of diamonds - wealth, legacy, long-term success",
    emoji: "🃊",
    suit: "Diamonds",
    rank: "10",
    element: "earth",
  },
  {
    name: "Jack of Diamonds",
    description: "The jack of diamonds - opportunity, new job, manifestation",
    emoji: "🃋",
    suit: "Diamonds",
    rank: "Jack",
    element: "earth",
  },
  {
    name: "Queen of Diamonds",
    description: "The queen of diamonds - practical, nurturing, financially secure",
    emoji: "🃍",
    suit: "Diamonds",
    rank: "Queen",
    element: "earth",
  },
  {
    name: "King of Diamonds",
    description: "The king of diamonds - abundance, security, financial control",
    emoji: "🃎",
    suit: "Diamonds",
    rank: "King",
    element: "earth",
  },
  
  // Clubs
  {
    name: "Ace of Clubs",
    description: "The ace of clubs - new opportunity, inspiration, creative spark",
    emoji: "🃑",
    suit: "Clubs",
    rank: "Ace",
    element: "fire",
  },
  {
    name: "Two of Clubs",
    description: "The two of clubs - planning, discovery, leaving comfort zone",
    emoji: "🃒",
    suit: "Clubs",
    rank: "2",
    element: "fire",
  },
  {
    name: "Three of Clubs",
    description: "The three of clubs - expansion, growth, looking ahead",
    emoji: "🃓",
    suit: "Clubs",
    rank: "3",
    element: "fire",
  },
  {
    name: "Four of Clubs",
    description: "The four of clubs - celebration, community, harmony",
    emoji: "🃔",
    suit: "Clubs",
    rank: "4",
    element: "fire",
  },
  {
    name: "Five of Clubs",
    description: "The five of clubs - competition, conflict, disagreement",
    emoji: "🃕",
    suit: "Clubs",
    rank: "5",
    element: "fire",
  },
  {
    name: "Six of Clubs",
    description: "The six of clubs - success, recognition, progress",
    emoji: "🃖",
    suit: "Clubs",
    rank: "6",
    element: "fire",
  },
  {
    name: "Seven of Clubs",
    description: "The seven of clubs - defending beliefs, standing ground, protection",
    emoji: "🃗",
    suit: "Clubs",
    rank: "7",
    element: "fire",
  },
  {
    name: "Eight of Clubs",
    description: "The eight of clubs - rapid action, movement, quick decisions",
    emoji: "🃘",
    suit: "Clubs",
    rank: "8",
    element: "fire",
  },
  {
    name: "Nine of Clubs",
    description: "The nine of clubs - resilience, persistence, last stand",
    emoji: "🃙",
    suit: "Clubs",
    rank: "9",
    element: "fire",
  },
  {
    name: "Ten of Clubs",
    description: "The ten of clubs - burden, responsibility, hard work",
    emoji: "🃚",
    suit: "Clubs",
    rank: "10",
    element: "fire",
  },
  {
    name: "Jack of Clubs",
    description: "The jack of clubs - exploration, excitement, inspiration",
    emoji: "🃛",
    suit: "Clubs",
    rank: "Jack",
    element: "fire",
  },
  {
    name: "Queen of Clubs",
    description: "The queen of clubs - courage, determination, confidence",
    emoji: "🃝",
    suit: "Clubs",
    rank: "Queen",
    element: "fire",
  },
  {
    name: "King of Clubs",
    description: "The king of clubs - leadership, vision, entrepreneurship",
    emoji: "🃞",
    suit: "Clubs",
    rank: "King",
    element: "fire",
  },
  
  // Spades
  {
    name: "Ace of Spades",
    description: "The ace of spades - breakthrough, clarity, truth",
    emoji: "🂡",
    suit: "Spades",
    rank: "Ace",
    element: "air",
  },
  {
    name: "Two of Spades",
    description: "The two of spades - difficult choices, indecision, stalemate",
    emoji: "🂢",
    suit: "Spades",
    rank: "2",
    element: "air",
  },
  {
    name: "Three of Spades",
    description: "The three of spades - heartbreak, emotional pain, sorrow",
    emoji: "🂣",
    suit: "Spades",
    rank: "3",
    element: "air",
  },
  {
    name: "Four of Spades",
    description: "The four of spades - rest, restoration, contemplation",
    emoji: "🂤",
    suit: "Spades",
    rank: "4",
    element: "air",
  },
  {
    name: "Five of Spades",
    description: "The five of spades - conflict, defeat, dishonor",
    emoji: "🂥",
    suit: "Spades",
    rank: "5",
    element: "air",
  },
  {
    name: "Six of Spades",
    description: "The six of spades - transition, moving on, leaving behind",
    emoji: "🂦",
    suit: "Spades",
    rank: "6",
    element: "air",
  },
  {
    name: "Seven of Spades",
    description: "The seven of spades - deception, strategy, betrayal",
    emoji: "🂧",
    suit: "Spades",
    rank: "7",
    element: "air",
  },
  {
    name: "Eight of Spades",
    description: "The eight of spades - imprisonment, restriction, self-victimization",
    emoji: "🂨",
    suit: "Spades",
    rank: "8",
    element: "air",
  },
  {
    name: "Nine of Spades",
    description: "The nine of spades - anxiety, worry, fear, nightmares",
    emoji: "🂩",
    suit: "Spades",
    rank: "9",
    element: "air",
  },
  {
    name: "Ten of Spades",
    description: "The ten of spades - betrayal, endings, crisis, loss",
    emoji: "🂪",
    suit: "Spades",
    rank: "10",
    element: "air",
  },
  {
    name: "Jack of Spades",
    description: "The jack of spades - new ideas, curiosity, communication",
    emoji: "🂫",
    suit: "Spades",
    rank: "Jack",
    element: "air",
  },
  {
    name: "Queen of Spades",
    description: "The queen of spades - independence, honesty, clear boundaries",
    emoji: "🂭",
    suit: "Spades",
    rank: "Queen",
    element: "air",
  },
  {
    name: "King of Spades",
    description: "The king of spades - mental clarity, authority, truth",
    emoji: "🂮",
    suit: "Spades",
    rank: "King",
    element: "air",
  },
];
