import miniB from "../../assets/performa.png";
import "./About.scss";

function About() {
  return (
    <div className="page-container">
      <div className="about">
        <div className="img-cont">
          <img src={miniB} alt="logo" className="mini-b" />
        </div>
        <div className="text-cont">
          <h1>Welcome to the Antigogglin.org</h1>
          <p>
            Hi, I am Brendan O'Keefe. I do software development for work but
            this site is for all my side projects, ideas, portfolio. ☮️
          </p>

          {/* Existing content */}
          <h1>Me</h1>
          <p>
            I am a very enthused software developer who loves complex problem
            solving and working on innovative teams. I really love the work of
            development and hope to stay coding forever!
          </p>
          <p>
            My favorite things about web development are when we can shorten the
            barriers to talking to each other, and uncomplicate systems that
            were previously bureaucratically complex and difficult to navigate.
          </p>
          <p>
            Outside of work, I concentrate on non-laptop hobbies like playing
            guitar, hiking, fermenting foods, growing plants in my garden and
            hydroponically, or reading first-contact explorer accounts or
            seafaring journals.
          </p>

          {/* New content */}
          <h1>How This App Is Powered by AI</h1>
          <p>
            At the core of my projects is an advanced artificial intelligence
            system that leverages the latest models and frameworks. Unlike
            traditional AI setups, this one is powered by a special AI solution
            that runs locally on my computer.
          </p>
          <p>
            What Makes It Special? This AI system is not just any ordinary
            model. It's designed to be solar-powered, capable of running
            entirely offline without the need for a constant internet
            connection. My setup is based on LM Studio and Bionic, which allows
            me to execute models locally on my laptop.
          </p>
          <p>
            The Power Source? The AI setup is powered by a state-of-the-art
            solar system located in my garage. This system consists of 6
            high-efficiency 200W panels, a hybrid inverter, and a large battery.
            The combination of these components ensures that my AI models are
            always ready to go, even on cloudy days or without a reliable power
            source.
          </p>
          <p>
            Integration with VS Code? To further enhance my workflow, I've
            integrated the AI system with the Continue plugin in Visual Studio
            Code. This integration allows me to generate code, debug it, and
            deploy it entirely from my local machine.
          </p>
          <p>
            A Greener Approach? By hosting my AI models locally, I've eliminated
            the need to rely on remote servers or cloud computing resources.
            This not only speeds up development and reduces latency but also
            significantly lowers my carbon footprint. The solar-powered system
            in my garage runs entirely off the energy generated by its panels,
            making it a truly sustainable solution.
          </p>
          <p>
            ^ that entire section is a little awkardly worded and incorrect in
            places but its the first completely locally-generated code added by
            an LLM here. -Brendan
          </p>
        </div>
      </div>
    </div>
  );
}

export default About;
