name: CI Pipeline

on:
  push:
    branches: 
      - "main"
      - "test/mysql-deploy" 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build -t ${{secrets.DOCKER_USERNAME}}/b-mono-image:latest .

    - name: Push to Dockerhub
      run: docker push ${{secrets.DOCKER_USERNAME}}/b-mono-image:latest