name: CI Pipeline

on:
  push:
    branches: [ "main", "feature/lunch-2" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        docker build -t ${{secrets.DOCKER_USERNAME}}/b-mono-image:${BRANCH_NAME} .
    - name: Push to Dockerhub
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        docker push ${{secrets.DOCKER_USERNAME}}/b-mono-image:${BRANCH_NAME}