name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.0'  # Specify your exact Node.js version

    - name: Install Root Dependencies
      run: npm install  # Installs dependencies defined in the root package.json

    - name: Clean and Install Frontend Dependencies
      run: |
        rm -rf ./react-fe/node_modules  # Remove existing node_modules for clean slate
        npm install --prefix ./react-fe  # Install dependencies from the react-fe directory

    - name: Build Frontend
      run: npm run build:fe  # Builds the React frontend

    - name: Install Nest Server Dependencies
      run: npm install --prefix ./nest-server

    - name: Start Backend Server
      run: npm run start:server 

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 692859927760.dkr.ecr.us-west-2.amazonaws.com

    - name: Build and Push Docker Images
      env:
        AWS_ACCOUNT_ID: 692859927760
        AWS_REGION: us-west-2
      run: |
        docker-compose build  # Use docker-compose to build both images
        # Tag and push nest-server (backend)
        docker tag b-mono_nest-server:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/bverse/b-mono:nest-server-latest
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/bverse/b-mono:nest-server-latest
        # Tag and push react-fe (frontend)
        docker tag b-mono_react-fe:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/bverse/b-mono:react-fe-latest
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/bverse/b-mono:react-fe-latest

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: arn:aws:ecs:us-west-2:692859927760:task-definition/b-mono-task-definition:5  # Point directly to your task definition name and its latest revision
        service: b-mono-service                   # Specify your ECS service name
        cluster: b-mono-cluster                   # Specify your ECS cluster
        desired-count: 1                          # Specify the desired count for your service
        wait-for-service-stability: true 